/**:
  ros__parameters:
    control_gains:
        K_p_x: 7.00
        K_p_y: 7.00
        K_p_z: 6.00
        K_v_x: 6.00
        K_v_y: 6.00
        K_v_z: 3.00
        K_R_x: 3.5
        K_R_y: 3.5
        K_R_z: 0.3
        K_w_x: 0.5
        K_w_y: 0.5
        K_w_z: 0.1